# OrePay Configuration
# Version 1.0.0

# Ore rewards - specify the amount of money given per each ore type
# Format: MATERIAL_NAME: reward_amount
ore-rewards:
  COAL_ORE: 2.0
  DEEPSLATE_COAL_ORE: 2.5
  IRON_ORE: 5.0
  DEEPSLATE_IRON_ORE: 6.0
  COPPER_ORE: 3.0
  DEEPSLATE_COPPER_ORE: 3.5
  GOLD_ORE: 8.0
  DEEPSLATE_GOLD_ORE: 10.0
  REDSTONE_ORE: 4.0
  DEEPSLATE_REDSTONE_ORE: 5.0
  LAPIS_ORE: 6.0
  DEEPSLATE_LAPIS_ORE: 7.0
  EMERALD_ORE: 15.0
  DEEPSLATE_EMERALD_ORE: 20.0
  DIAMOND_ORE: 25.0
  DEEPSLATE_DIAMOND_ORE: 30.0
  NETHER_GOLD_ORE: 4.0
  NETHER_QUARTZ_ORE: 3.0
  ANCIENT_DEBRIS: 50.0

# Plugin settings
settings:
  # Whether to show reward messages when mining ores
  show-reward-messages: true
  
  # Message template for rewards
  # Available placeholders:
  # {amount} - the amount of money rewarded
  # {ore} - the name of the ore mined
  reward-message: "ยงa+{amount} coins ยง7(mined {ore})"

# Don't change this
config-version: 1
